services:
    offtune.last_route_event_listener:
        class: Offtune\HelperBundle\EventListener\LastRouteListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }

    session_entity_manager:
        class: Offtune\HelperBundle\Services\SessionEntityManager
        arguments:
            - "@request_stack"
            - "@logger"
